version: '3.7'

services:
  web:
    image          : ${IMAGE_NAME}
    container_name : ${CONTAINER_NAME}
    environment:
      - PYTHONPATH=/app
    ports:
      - ${API_PORT}:5000
    restart: unless-stopped
